export const PRODUCTS = [
  // Fruits & Veggies (25 products)
  {
    id: 1,
    name: "Fresh Red Apples",
    price: 129,
    originalPrice: 159,
    category: "Fruits & Veggies",
    rating: 4.5,
    reviews: 120,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Fresh+Red+Apples",
    description: "Fresh, crispy red apples from Kashmir",
    unit: "1 kg",
  },
  {
    id: 2,
    name: "Fresh Bananas",
    price: 59,
    originalPrice: 69,
    category: "Fruits & Veggies",
    rating: 4.6,
    reviews: 156,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Fresh+Bananas",
    description: "Fresh ripe bananas",
    unit: "1 dozen",
  },
  {
    id: 3,
    name: "Green Spinach",
    price: 39,
    originalPrice: 49,
    category: "Fruits & Veggies",
    rating: 4.3,
    reviews: 89,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Green+Spinach",
    description: "Fresh green spinach leaves",
    unit: "250g",
  },
  {
    id: 4,
    name: "Fresh Tomatoes",
    price: 79,
    originalPrice: 89,
    category: "Fruits & Veggies",
    rating: 4.4,
    reviews: 134,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Fresh+Tomatoes",
    description: "Fresh red tomatoes",
    unit: "1 kg",
  },
  {
    id: 5,
    name: "Fresh Onions",
    price: 49,
    originalPrice: 59,
    category: "Fruits & Veggies",
    rating: 4.2,
    reviews: 98,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Fresh+Onions",
    description: "Fresh red onions",
    unit: "1 kg",
  },
  {
    id: 6,
    name: "Fresh Potatoes",
    price: 39,
    originalPrice: 49,
    category: "Fruits & Veggies",
    rating: 4.1,
    reviews: 76,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Fresh+Potatoes",
    description: "Fresh potatoes",
    unit: "1 kg",
  },
  {
    id: 7,
    name: "Fresh Carrots",
    price: 69,
    originalPrice: 79,
    category: "Fruits & Veggies",
    rating: 4.5,
    reviews: 112,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Fresh+Carrots",
    description: "Fresh orange carrots",
    unit: "500g",
  },
  {
    id: 8,
    name: "Fresh Oranges",
    price: 99,
    originalPrice: 119,
    category: "Fruits & Veggies",
    rating: 4.6,
    reviews: 145,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Fresh+Oranges",
    description: "Sweet fresh oranges",
    unit: "1 kg",
  },
  {
    id: 9,
    name: "Fresh Mangoes",
    price: 199,
    originalPrice: 229,
    category: "Fruits & Veggies",
    rating: 4.8,
    reviews: 203,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Fresh+Mangoes",
    description: "Sweet Alphonso mangoes",
    unit: "1 kg",
  },
  {
    id: 10,
    name: "Fresh Grapes",
    price: 149,
    originalPrice: 169,
    category: "Fruits & Veggies",
    rating: 4.4,
    reviews: 87,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Fresh+Grapes",
    description: "Sweet green grapes",
    unit: "500g",
  },
  {
    id: 11,
    name: "Fresh Lemons",
    price: 29,
    originalPrice: 39,
    category: "Fruits & Veggies",
    rating: 4.2,
    reviews: 65,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Fresh+Lemons",
    description: "Fresh lemons",
    unit: "250g",
  },
  {
    id: 12,
    name: "Fresh Cucumber",
    price: 39,
    originalPrice: 49,
    category: "Fruits & Veggies",
    rating: 4.1,
    reviews: 54,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Fresh+Cucumber",
    description: "Fresh green cucumber",
    unit: "500g",
  },
  {
    id: 13,
    name: "Fresh Capsicum",
    price: 89,
    originalPrice: 99,
    category: "Fruits & Veggies",
    rating: 4.3,
    reviews: 78,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Fresh+Capsicum",
    description: "Fresh green capsicum",
    unit: "500g",
  },
  {
    id: 14,
    name: "Fresh Cauliflower",
    price: 59,
    originalPrice: 69,
    category: "Fruits & Veggies",
    rating: 4.2,
    reviews: 92,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Fresh+Cauliflower",
    description: "Fresh white cauliflower",
    unit: "1 piece",
  },
  {
    id: 15,
    name: "Fresh Cabbage",
    price: 49,
    originalPrice: 59,
    category: "Fruits & Veggies",
    rating: 4.0,
    reviews: 67,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Fresh+Cabbage",
    description: "Fresh green cabbage",
    unit: "1 piece",
  },
  {
    id: 16,
    name: "Fresh Broccoli",
    price: 99,
    originalPrice: 119,
    category: "Fruits & Veggies",
    rating: 4.4,
    reviews: 83,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Fresh+Broccoli",
    description: "Fresh green broccoli",
    unit: "500g",
  },
  {
    id: 17,
    name: "Fresh Pineapple",
    price: 79,
    originalPrice: 99,
    category: "Fruits & Veggies",
    rating: 4.5,
    reviews: 156,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Fresh+Pineapple",
    description: "Sweet fresh pineapple",
    unit: "1 piece",
  },
  {
    id: 18,
    name: "Fresh Watermelon",
    price: 39,
    originalPrice: 49,
    category: "Fruits & Veggies",
    rating: 4.6,
    reviews: 234,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Fresh+Watermelon",
    description: "Sweet red watermelon",
    unit: "1 kg",
  },
  {
    id: 19,
    name: "Fresh Papaya",
    price: 69,
    originalPrice: 79,
    category: "Fruits & Veggies",
    rating: 4.3,
    reviews: 98,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Fresh+Papaya",
    description: "Sweet fresh papaya",
    unit: "1 kg",
  },
  {
    id: 20,
    name: "Fresh Pomegranate",
    price: 199,
    originalPrice: 229,
    category: "Fruits & Veggies",
    rating: 4.7,
    reviews: 167,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Fresh+Pomegranate",
    description: "Fresh red pomegranate",
    unit: "500g",
  },
  {
    id: 21,
    name: "Fresh Ginger",
    price: 89,
    originalPrice: 99,
    category: "Fruits & Veggies",
    rating: 4.2,
    reviews: 45,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Fresh+Ginger",
    description: "Fresh ginger root",
    unit: "250g",
  },
  {
    id: 22,
    name: "Fresh Garlic",
    price: 149,
    originalPrice: 169,
    category: "Fruits & Veggies",
    rating: 4.3,
    reviews: 67,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Fresh+Garlic",
    description: "Fresh garlic bulbs",
    unit: "250g",
  },
  {
    id: 23,
    name: "Fresh Mint Leaves",
    price: 19,
    originalPrice: 29,
    category: "Fruits & Veggies",
    rating: 4.4,
    reviews: 34,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Fresh+Mint",
    description: "Fresh mint leaves",
    unit: "100g",
  },
  {
    id: 24,
    name: "Fresh Coriander",
    price: 19,
    originalPrice: 29,
    category: "Fruits & Veggies",
    rating: 4.1,
    reviews: 56,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Fresh+Coriander",
    description: "Fresh coriander leaves",
    unit: "100g",
  },
  {
    id: 25,
    name: "Fresh Green Chili",
    price: 39,
    originalPrice: 49,
    category: "Fruits & Veggies",
    rating: 4.0,
    reviews: 78,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Green+Chili",
    description: "Fresh green chilies",
    unit: "250g",
  },

  // Dairy & Eggs (20 products)
  {
    id: 26,
    name: "Organic Milk",
    price: 79,
    originalPrice: 89,
    category: "Dairy & Eggs",
    rating: 4.8,
    reviews: 95,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Organic+Milk",
    description: "Fresh organic milk from local farms",
    unit: "1 L",
  },
  {
    id: 27,
    name: "Greek Yogurt",
    price: 89,
    originalPrice: 99,
    category: "Dairy & Eggs",
    rating: 4.4,
    reviews: 78,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Greek+Yogurt",
    description: "Thick and creamy Greek yogurt",
    unit: "200g",
  },
  {
    id: 28,
    name: "Fresh Eggs",
    price: 89,
    originalPrice: 99,
    category: "Dairy & Eggs",
    rating: 4.6,
    reviews: 234,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Fresh+Eggs",
    description: "Farm fresh eggs",
    unit: "12 pieces",
  },
  {
    id: 29,
    name: "Paneer",
    price: 149,
    originalPrice: 169,
    category: "Dairy & Eggs",
    rating: 4.5,
    reviews: 156,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Fresh+Paneer",
    description: "Fresh cottage cheese",
    unit: "200g",
  },
  {
    id: 30,
    name: "Butter",
    price: 199,
    originalPrice: 219,
    category: "Dairy & Eggs",
    rating: 4.3,
    reviews: 89,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Fresh+Butter",
    description: "Fresh white butter",
    unit: "500g",
  },
  {
    id: 31,
    name: "Cheese Slices",
    price: 129,
    originalPrice: 149,
    category: "Dairy & Eggs",
    rating: 4.4,
    reviews: 67,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Cheese+Slices",
    description: "Processed cheese slices",
    unit: "200g",
  },
  {
    id: 32,
    name: "Curd",
    price: 49,
    originalPrice: 59,
    category: "Dairy & Eggs",
    rating: 4.2,
    reviews: 123,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Fresh+Curd",
    description: "Fresh homemade curd",
    unit: "500g",
  },
  {
    id: 33,
    name: "Cream",
    price: 89,
    originalPrice: 99,
    category: "Dairy & Eggs",
    rating: 4.1,
    reviews: 45,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Fresh+Cream",
    description: "Fresh dairy cream",
    unit: "200ml",
  },
  {
    id: 34,
    name: "Mozzarella Cheese",
    price: 199,
    originalPrice: 229,
    category: "Dairy & Eggs",
    rating: 4.6,
    reviews: 78,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Mozzarella",
    description: "Fresh mozzarella cheese",
    unit: "200g",
  },
  {
    id: 35,
    name: "Buttermilk",
    price: 39,
    originalPrice: 49,
    category: "Dairy & Eggs",
    rating: 4.3,
    reviews: 56,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Buttermilk",
    description: "Fresh buttermilk",
    unit: "500ml",
  },
  {
    id: 36,
    name: "Ghee",
    price: 399,
    originalPrice: 449,
    category: "Dairy & Eggs",
    rating: 4.7,
    reviews: 189,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Pure+Ghee",
    description: "Pure cow ghee",
    unit: "500g",
  },
  {
    id: 37,
    name: "Milk Powder",
    price: 299,
    originalPrice: 329,
    category: "Dairy & Eggs",
    rating: 4.2,
    reviews: 67,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Milk+Powder",
    description: "Full cream milk powder",
    unit: "500g",
  },
  {
    id: 38,
    name: "Condensed Milk",
    price: 89,
    originalPrice: 99,
    category: "Dairy & Eggs",
    rating: 4.4,
    reviews: 45,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Condensed+Milk",
    description: "Sweetened condensed milk",
    unit: "400g",
  },
  {
    id: 39,
    name: "Ice Cream",
    price: 149,
    originalPrice: 169,
    category: "Dairy & Eggs",
    rating: 4.5,
    reviews: 234,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Ice+Cream",
    description: "Vanilla ice cream",
    unit: "500ml",
  },
  {
    id: 40,
    name: "Lassi",
    price: 59,
    originalPrice: 69,
    category: "Dairy & Eggs",
    rating: 4.3,
    reviews: 89,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Sweet+Lassi",
    description: "Sweet mango lassi",
    unit: "200ml",
  },
  {
    id: 41,
    name: "Cottage Cheese",
    price: 129,
    originalPrice: 149,
    category: "Dairy & Eggs",
    rating: 4.2,
    reviews: 56,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Cottage+Cheese",
    description: "Fresh cottage cheese",
    unit: "200g",
  },
  {
    id: 42,
    name: "Sour Cream",
    price: 99,
    originalPrice: 119,
    category: "Dairy & Eggs",
    rating: 4.1,
    reviews: 34,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Sour+Cream",
    description: "Fresh sour cream",
    unit: "200g",
  },
  {
    id: 43,
    name: "Whipped Cream",
    price: 119,
    originalPrice: 139,
    category: "Dairy & Eggs",
    rating: 4.4,
    reviews: 67,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Whipped+Cream",
    description: "Fresh whipped cream",
    unit: "200ml",
  },
  {
    id: 44,
    name: "Flavored Milk",
    price: 49,
    originalPrice: 59,
    category: "Dairy & Eggs",
    rating: 4.3,
    reviews: 123,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Flavored+Milk",
    description: "Chocolate flavored milk",
    unit: "200ml",
  },
  {
    id: 45,
    name: "Probiotic Drink",
    price: 69,
    originalPrice: 79,
    category: "Dairy & Eggs",
    rating: 4.2,
    reviews: 45,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Probiotic+Drink",
    description: "Healthy probiotic drink",
    unit: "200ml",
  },

  // Beverages (20 products)
  {
    id: 46,
    name: "Premium Green Tea",
    price: 199,
    originalPrice: 249,
    category: "Beverages",
    rating: 4.3,
    reviews: 83,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Green+Tea",
    description: "Premium quality green tea leaves",
    unit: "100g",
  },
  {
    id: 47,
    name: "Orange Juice",
    price: 149,
    originalPrice: 179,
    category: "Beverages",
    rating: 4.3,
    reviews: 89,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Orange+Juice",
    description: "Fresh squeezed orange juice",
    unit: "1 L",
  },
  {
    id: 48,
    name: "Coffee Beans",
    price: 299,
    originalPrice: 349,
    category: "Beverages",
    rating: 4.6,
    reviews: 156,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Coffee+Beans",
    description: "Premium arabica coffee beans",
    unit: "250g",
  },
  {
    id: 49,
    name: "Black Tea",
    price: 149,
    originalPrice: 169,
    category: "Beverages",
    rating: 4.2,
    reviews: 67,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Black+Tea",
    description: "Premium black tea leaves",
    unit: "250g",
  },
  {
    id: 50,
    name: "Energy Drink",
    price: 89,
    originalPrice: 99,
    category: "Beverages",
    rating: 4.1,
    reviews: 234,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Energy+Drink",
    description: "Refreshing energy drink",
    unit: "250ml",
  },
  {
    id: 51,
    name: "Coconut Water",
    price: 59,
    originalPrice: 69,
    category: "Beverages",
    rating: 4.4,
    reviews: 123,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Coconut+Water",
    description: "Natural coconut water",
    unit: "200ml",
  },
  {
    id: 52,
    name: "Soft Drink",
    price: 49,
    originalPrice: 59,
    category: "Beverages",
    rating: 4.0,
    reviews: 345,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Soft+Drink",
    description: "Refreshing cola drink",
    unit: "500ml",
  },
  {
    id: 53,
    name: "Lemon Juice",
    price: 39,
    originalPrice: 49,
    category: "Beverages",
    rating: 4.2,
    reviews: 78,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Lemon+Juice",
    description: "Fresh lemon juice",
    unit: "200ml",
  },
  {
    id: 54,
    name: "Mango Juice",
    price: 89,
    originalPrice: 99,
    category: "Beverages",
    rating: 4.5,
    reviews: 167,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Mango+Juice",
    description: "Fresh mango juice",
    unit: "500ml",
  },
  {
    id: 55,
    name: "Apple Juice",
    price: 79,
    originalPrice: 89,
    category: "Beverages",
    rating: 4.3,
    reviews: 89,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Apple+Juice",
    description: "Fresh apple juice",
    unit: "500ml",
  },
  {
    id: 56,
    name: "Sports Drink",
    price: 69,
    originalPrice: 79,
    category: "Beverages",
    rating: 4.1,
    reviews: 56,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Sports+Drink",
    description: "Electrolyte sports drink",
    unit: "500ml",
  },
  {
    id: 57,
    name: "Herbal Tea",
    price: 179,
    originalPrice: 199,
    category: "Beverages",
    rating: 4.4,
    reviews: 45,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Herbal+Tea",
    description: "Organic herbal tea blend",
    unit: "100g",
  },
  {
    id: 58,
    name: "Iced Tea",
    price: 59,
    originalPrice: 69,
    category: "Beverages",
    rating: 4.2,
    reviews: 123,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Iced+Tea",
    description: "Refreshing iced tea",
    unit: "500ml",
  },
  {
    id: 59,
    name: "Protein Shake",
    price: 199,
    originalPrice: 229,
    category: "Beverages",
    rating: 4.3,
    reviews: 67,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Protein+Shake",
    description: "Chocolate protein shake",
    unit: "500ml",
  },
  {
    id: 60,
    name: "Smoothie",
    price: 129,
    originalPrice: 149,
    category: "Beverages",
    rating: 4.5,
    reviews: 89,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Berry+Smoothie",
    description: "Mixed berry smoothie",
    unit: "300ml",
  },
  {
    id: 61,
    name: "Mineral Water",
    price: 29,
    originalPrice: 39,
    category: "Beverages",
    rating: 4.0,
    reviews: 234,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Mineral+Water",
    description: "Pure mineral water",
    unit: "1 L",
  },
  {
    id: 62,
    name: "Flavored Water",
    price: 49,
    originalPrice: 59,
    category: "Beverages",
    rating: 4.1,
    reviews: 78,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Flavored+Water",
    description: "Lemon flavored water",
    unit: "500ml",
  },
  {
    id: 63,
    name: "Hot Chocolate",
    price: 89,
    originalPrice: 99,
    category: "Beverages",
    rating: 4.4,
    reviews: 56,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Hot+Chocolate",
    description: "Rich hot chocolate mix",
    unit: "200g",
  },
  {
    id: 64,
    name: "Instant Coffee",
    price: 199,
    originalPrice: 219,
    category: "Beverages",
    rating: 4.2,
    reviews: 123,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Instant+Coffee",
    description: "Premium instant coffee",
    unit: "200g",
  },
  {
    id: 65,
    name: "Cold Brew Coffee",
    price: 149,
    originalPrice: 169,
    category: "Beverages",
    rating: 4.5,
    reviews: 67,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Cold+Brew",
    description: "Ready to drink cold brew",
    unit: "500ml",
  },

  // Snacks (15 products)
  {
    id: 66,
    name: "Mixed Nuts",
    price: 299,
    originalPrice: 349,
    category: "Snacks",
    rating: 4.7,
    reviews: 112,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Mixed+Nuts",
    description: "Premium mixed nuts and dry fruits",
    unit: "250g",
  },
  {
    id: 67,
    name: "Potato Chips",
    price: 49,
    originalPrice: 59,
    category: "Snacks",
    rating: 4.2,
    reviews: 234,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Potato+Chips",
    description: "Crispy salted potato chips",
    unit: "100g",
  },
  {
    id: 68,
    name: "Cookies",
    price: 89,
    originalPrice: 99,
    category: "Snacks",
    rating: 4.4,
    reviews: 156,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Cookies",
    description: "Chocolate chip cookies",
    unit: "200g",
  },
  {
    id: 69,
    name: "Popcorn",
    price: 69,
    originalPrice: 79,
    category: "Snacks",
    rating: 4.1,
    reviews: 89,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Popcorn",
    description: "Butter flavored popcorn",
    unit: "100g",
  },
  {
    id: 70,
    name: "Crackers",
    price: 59,
    originalPrice: 69,
    category: "Snacks",
    rating: 4.0,
    reviews: 67,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Crackers",
    description: "Whole wheat crackers",
    unit: "150g",
  },
  {
    id: 71,
    name: "Chocolate Bar",
    price: 79,
    originalPrice: 89,
    category: "Snacks",
    rating: 4.5,
    reviews: 345,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Chocolate+Bar",
    description: "Dark chocolate bar",
    unit: "100g",
  },
  {
    id: 72,
    name: "Granola Bar",
    price: 99,
    originalPrice: 119,
    category: "Snacks",
    rating: 4.3,
    reviews: 78,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Granola+Bar",
    description: "Healthy granola bar",
    unit: "6 pieces",
  },
  {
    id: 73,
    name: "Trail Mix",
    price: 199,
    originalPrice: 229,
    category: "Snacks",
    rating: 4.6,
    reviews: 123,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Trail+Mix",
    description: "Nuts and dried fruits mix",
    unit: "200g",
  },
  {
    id: 74,
    name: "Pretzels",
    price: 89,
    originalPrice: 99,
    category: "Snacks",
    rating: 4.2,
    reviews: 56,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Pretzels",
    description: "Salted pretzels",
    unit: "150g",
  },
  {
    id: 75,
    name: "Dried Fruits",
    price: 249,
    originalPrice: 279,
    category: "Snacks",
    rating: 4.4,
    reviews: 89,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Dried+Fruits",
    description: "Mixed dried fruits",
    unit: "200g",
  },
  {
    id: 76,
    name: "Protein Bar",
    price: 149,
    originalPrice: 169,
    category: "Snacks",
    rating: 4.3,
    reviews: 67,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Protein+Bar",
    description: "High protein energy bar",
    unit: "60g",
  },
  {
    id: 77,
    name: "Rice Cakes",
    price: 79,
    originalPrice: 89,
    category: "Snacks",
    rating: 4.1,
    reviews: 45,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Rice+Cakes",
    description: "Plain rice cakes",
    unit: "100g",
  },
  {
    id: 78,
    name: "Nuts & Seeds",
    price: 199,
    originalPrice: 229,
    category: "Snacks",
    rating: 4.5,
    reviews: 78,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Nuts+Seeds",
    description: "Mixed nuts and seeds",
    unit: "150g",
  },
  {
    id: 79,
    name: "Fruit Chips",
    price: 129,
    originalPrice: 149,
    category: "Snacks",
    rating: 4.2,
    reviews: 56,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Fruit+Chips",
    description: "Dehydrated fruit chips",
    unit: "100g",
  },
  {
    id: 80,
    name: "Energy Balls",
    price: 149,
    originalPrice: 169,
    category: "Snacks",
    rating: 4.4,
    reviews: 89,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Energy+Balls",
    description: "Date and nut energy balls",
    unit: "200g",
  },

  // Bakery (10 products)
  {
    id: 81,
    name: "Whole Wheat Bread",
    price: 49,
    originalPrice: 59,
    category: "Bakery",
    rating: 4.2,
    reviews: 75,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Wheat+Bread",
    description: "Fresh whole wheat bread",
    unit: "400g",
  },
  {
    id: 82,
    name: "Croissants",
    price: 129,
    originalPrice: 149,
    category: "Bakery",
    rating: 4.5,
    reviews: 89,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Croissants",
    description: "Buttery fresh croissants",
    unit: "4 pieces",
  },
  {
    id: 83,
    name: "Muffins",
    price: 99,
    originalPrice: 119,
    category: "Bakery",
    rating: 4.3,
    reviews: 67,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Blueberry+Muffins",
    description: "Blueberry muffins",
    unit: "4 pieces",
  },
  {
    id: 84,
    name: "Bagels",
    price: 89,
    originalPrice: 99,
    category: "Bakery",
    rating: 4.1,
    reviews: 45,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Bagels",
    description: "Fresh sesame bagels",
    unit: "4 pieces",
  },
  {
    id: 85,
    name: "Donuts",
    price: 149,
    originalPrice: 169,
    category: "Bakery",
    rating: 4.4,
    reviews: 123,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Glazed+Donuts",
    description: "Glazed donuts",
    unit: "6 pieces",
  },
  {
    id: 86,
    name: "Cake Slice",
    price: 79,
    originalPrice: 89,
    category: "Bakery",
    rating: 4.6,
    reviews: 156,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Chocolate+Cake",
    description: "Chocolate cake slice",
    unit: "1 piece",
  },
  {
    id: 87,
    name: "Pastries",
    price: 69,
    originalPrice: 79,
    category: "Bakery",
    rating: 4.2,
    reviews: 78,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Pastries",
    description: "Assorted pastries",
    unit: "2 pieces",
  },
  {
    id: 88,
    name: "Sandwich Bread",
    price: 39,
    originalPrice: 49,
    category: "Bakery",
    rating: 4.0,
    reviews: 234,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Sandwich+Bread",
    description: "White sandwich bread",
    unit: "400g",
  },
  {
    id: 89,
    name: "Dinner Rolls",
    price: 59,
    originalPrice: 69,
    category: "Bakery",
    rating: 4.1,
    reviews: 56,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Dinner+Rolls",
    description: "Soft dinner rolls",
    unit: "6 pieces",
  },
  {
    id: 90,
    name: "Pita Bread",
    price: 49,
    originalPrice: 59,
    category: "Bakery",
    rating: 4.2,
    reviews: 67,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Pita+Bread",
    description: "Fresh pita bread",
    unit: "4 pieces",
  },

  // Personal Care (10 products)
  {
    id: 91,
    name: "Toilet Paper Roll",
    price: 99,
    originalPrice: 119,
    category: "Personal Care",
    rating: 4.1,
    reviews: 67,
    inStock: false,
    image: "/placeholder.svg?height=200&width=200&text=Toilet+Paper",
    description: "Soft 3-ply toilet paper",
    unit: "4 rolls",
  },
  {
    id: 92,
    name: "Shampoo",
    price: 199,
    originalPrice: 229,
    category: "Personal Care",
    rating: 4.3,
    reviews: 89,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Shampoo",
    description: "Anti-dandruff shampoo",
    unit: "400ml",
  },
  {
    id: 93,
    name: "Toothpaste",
    price: 89,
    originalPrice: 99,
    category: "Personal Care",
    rating: 4.4,
    reviews: 156,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Toothpaste",
    description: "Fluoride toothpaste",
    unit: "100g",
  },
  {
    id: 94,
    name: "Body Wash",
    price: 149,
    originalPrice: 169,
    category: "Personal Care",
    rating: 4.2,
    reviews: 78,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Body+Wash",
    description: "Moisturizing body wash",
    unit: "500ml",
  },
  {
    id: 95,
    name: "Face Cream",
    price: 299,
    originalPrice: 349,
    category: "Personal Care",
    rating: 4.5,
    reviews: 123,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Face+Cream",
    description: "Anti-aging face cream",
    unit: "50g",
  },
  {
    id: 96,
    name: "Deodorant",
    price: 129,
    originalPrice: 149,
    category: "Personal Care",
    rating: 4.1,
    reviews: 67,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Deodorant",
    description: "24-hour protection deodorant",
    unit: "150ml",
  },
  {
    id: 97,
    name: "Hand Sanitizer",
    price: 79,
    originalPrice: 89,
    category: "Personal Care",
    rating: 4.3,
    reviews: 234,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Hand+Sanitizer",
    description: "70% alcohol hand sanitizer",
    unit: "500ml",
  },
  {
    id: 98,
    name: "Soap",
    price: 39,
    originalPrice: 49,
    category: "Personal Care",
    rating: 4.0,
    reviews: 89,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Soap",
    description: "Antibacterial soap",
    unit: "125g",
  },
  {
    id: 99,
    name: "Tissues",
    price: 49,
    originalPrice: 59,
    category: "Personal Care",
    rating: 4.2,
    reviews: 56,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Tissues",
    description: "Soft facial tissues",
    unit: "100 sheets",
  },
  {
    id: 100,
    name: "Moisturizer",
    price: 199,
    originalPrice: 229,
    category: "Personal Care",
    rating: 4.4,
    reviews: 78,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Moisturizer",
    description: "Daily moisturizing lotion",
    unit: "200ml",
  },

  // Grocery (10 products)
  {
    id: 101,
    name: "Natural Honey",
    price: 299,
    originalPrice: 349,
    category: "Grocery",
    rating: 4.9,
    reviews: 134,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Natural+Honey",
    description: "Pure natural honey from Himalayas",
    unit: "500g",
  },
  {
    id: 102,
    name: "Olive Oil",
    price: 399,
    originalPrice: 449,
    category: "Grocery",
    rating: 4.6,
    reviews: 89,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Olive+Oil",
    description: "Extra virgin olive oil",
    unit: "500ml",
  },
  {
    id: 103,
    name: "Basmati Rice",
    price: 199,
    originalPrice: 229,
    category: "Grocery",
    rating: 4.5,
    reviews: 156,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Basmati+Rice",
    description: "Premium basmati rice",
    unit: "1 kg",
  },
  {
    id: 104,
    name: "Whole Wheat Flour",
    price: 89,
    originalPrice: 99,
    category: "Grocery",
    rating: 4.3,
    reviews: 78,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Wheat+Flour",
    description: "Fresh whole wheat flour",
    unit: "1 kg",
  },
  {
    id: 105,
    name: "Sugar",
    price: 49,
    originalPrice: 59,
    category: "Grocery",
    rating: 4.1,
    reviews: 234,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Sugar",
    description: "White refined sugar",
    unit: "1 kg",
  },
  {
    id: 106,
    name: "Salt",
    price: 29,
    originalPrice: 39,
    category: "Grocery",
    rating: 4.0,
    reviews: 123,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Salt",
    description: "Iodized table salt",
    unit: "1 kg",
  },
  {
    id: 107,
    name: "Cooking Oil",
    price: 149,
    originalPrice: 169,
    category: "Grocery",
    rating: 4.2,
    reviews: 89,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Cooking+Oil",
    description: "Refined sunflower oil",
    unit: "1 L",
  },
  {
    id: 108,
    name: "Spice Mix",
    price: 79,
    originalPrice: 89,
    category: "Grocery",
    rating: 4.4,
    reviews: 67,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Spice+Mix",
    description: "Garam masala spice mix",
    unit: "100g",
  },
  {
    id: 109,
    name: "Pasta",
    price: 99,
    originalPrice: 119,
    category: "Grocery",
    rating: 4.3,
    reviews: 56,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Pasta",
    description: "Whole wheat pasta",
    unit: "500g",
  },
  {
    id: 110,
    name: "Canned Beans",
    price: 69,
    originalPrice: 79,
    category: "Grocery",
    rating: 4.1,
    reviews: 45,
    inStock: true,
    image: "/placeholder.svg?height=200&width=200&text=Canned+Beans",
    description: "Red kidney beans",
    unit: "400g",
  },
]

export const CATEGORIES = [
  {
    name: "Fruits & Veggies",
    icon: "🥕",
    color: "from-green-500 to-emerald-500",
    image: "/placeholder.svg?height=100&width=100&text=Fruits",
  },
  {
    name: "Dairy & Eggs",
    icon: "🥛",
    color: "from-blue-500 to-cyan-500",
    image: "/placeholder.svg?height=100&width=100&text=Dairy",
  },
  {
    name: "Snacks",
    icon: "🍿",
    color: "from-orange-500 to-red-500",
    image: "/placeholder.svg?height=100&width=100&text=Snacks",
  },
  {
    name: "Beverages",
    icon: "🥤",
    color: "from-purple-500 to-pink-500",
    image: "/placeholder.svg?height=100&width=100&text=Beverages",
  },
  {
    name: "Personal Care",
    icon: "🧴",
    color: "from-teal-500 to-green-500",
    image: "/placeholder.svg?height=100&width=100&text=Personal",
  },
  {
    name: "Household",
    icon: "🧽",
    color: "from-indigo-500 to-purple-500",
    image: "/placeholder.svg?height=100&width=100&text=Household",
  },
  {
    name: "Bakery",
    icon: "🍞",
    color: "from-yellow-500 to-orange-500",
    image: "/placeholder.svg?height=100&width=100&text=Bakery",
  },
  {
    name: "Grocery",
    icon: "🛒",
    color: "from-pink-500 to-rose-500",
    image: "/placeholder.svg?height=100&width=100&text=Grocery",
  },
]
